language: c
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update
  - sudo pip install cpp-coveralls

script: gcc -v && mkdir build && cd build && cmake .. && make VERBOSE=1 && test/base && test/waiters && test/channel && test/locks && test/pool && test/asyncio && test/bench && test/wait && test/log_stdout

compiler:
  - gcc
  - clang

env:
  - CFLAGS="-O3"
  - CFLAGS="-O0 --coverage -DCOVERAGE" LDFLAGS="--coverage" COVERAGE=1

after_success:
  - '[ -n "$COVERAGE" ] && coveralls --exclude test --exclude include --exclude src/http_parser.c'
