language: c
dist: trusty

script: gcc -v && mkdir build && cd build && cmake .. && make VERBOSE=1 && test/base && test/waiters && test/channel && test/locks && test/pool && test/asyncio && test/bench && test/wait && test/log_stdout

compiler:
  - gcc
  - clang

env:
  - CFLAGS="-O3"
